<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Plugin.Fingerprint" Version="2.1.5" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
    <PackageReference Include="Xamarin.Essentials" Version="1.8.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EOM.TSHotelManagementSystem.Mobile.Common.Utility\EOM.TSHotelManagementSystem.Mobile.Common.Utility.csproj" />
    <ProjectReference Include="..\EOM.TSHotelManagementSystem.Mobile.Contract\EOM.TSHotelManagementSystem.Mobile.Contract.csproj" />
  </ItemGroup>

</Project>
